spring.application.name=validator

#RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret

server.port=8081

spring.docker.compose.enabled=false